export const GET_TEMPERATURE_REQUEST = 'GET_TEMPERATURE_REQUEST'
export const GET_TEMPERATURE_SUCCESS = 'GET_TEMPERATURE_SUCCESS'
export const GET_TEMPERATURE_FAIL = 'GET_TEMPERATURE_FAIL'

export const CREATE_TEMPERATURE_REQUEST = 'CREATE_TEMPERATURE_REQUEST'
export const CREATE_TEMPERATURE_SUCCESS = 'CREATE_TEMPERATURE_SUCCESS'
export const CREATE_TEMPERATURE_FAIL = 'CREATE_TEMPERATURE_FAIL'
